# Generated by Django 5.0.6 on 2024-08-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_initial_deposit_date_userbankaccount_initial_deposite_date_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='core.bank'),
        ),
    ]
