# Generated by Django 5.0.6 on 2024-07-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbankaccount_bank'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, default='Mamar Bank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='core.bank'),
        ),
    ]
