# Generated by Django 5.0.6 on 2024-08-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
